name: test workflow 
on: 
  push:
    branches: 
      - dev 
      - main  
jobs: 
  example-job:  
    runs-on: ubuntu-latest  
    steps: 
      - name: print a welcome message 
        run: echo "welcome to my firdt workflow from youusef taha " 
      - name: checkout repo 
        uses: actions/checkout@v5.0.0  
      - name: list a repo 
        run: ls -la 


        uses: actions/checkout@v5.0.0  
      - name: list repo files 
        run: ls -la 
